server {
    listen 8080;

    # Serve Vue app at /gene2phenotype/
    location /gene2phenotype/ {
        alias /usr/share/nginx/html/gene2phenotype/;
        try_files $uri $uri/ @fallback;
    }

    location @fallback {
        rewrite ^ /gene2phenotype/index.html last;
    }
}
